name: Provisioning on Linux

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Provisioning
      run: |
        ./init.sh
