name: Provisioning on Linux

on:
  push:
  schedule:
    - cron: 00 14 * * 1

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Provisioning
      run: |
        ./init.sh
